### ISSUE TITLE
ECONNREFUSED connect ECONNREFUSED

### ISSUE THREAD

**Issue by mrzmyr** [andresdominguez/elementor#3]
Fresh installed the CLI bin by `sudo npm i -g elementor` and tried opening a remote selenium instance by `elementor <ip>:<port>` and I get this error:

```
/usr/local/lib/node_modules/elementor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
      throw error;
            ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/elementor/node_modules/selenium-webdriver/http/index.js:145:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
```

**Comment by andresdominguez** [comment]
Did you start the selenium server? Try to run elementor without arguments and then enter the URL in the browser. Does it launch chrome?

**Comment by mrzmyr** [comment]
Yes, started the selenium server on a remote PC. When running the `webdriver-manager` locally it works.

**Comment by andresdominguez** [comment]
I will refactor the code to accept flags or a protractor config file. 

I will make elementor launch the chrome browser without using the selenium server. 

Would you use elementor in another browser? The server is needed if you want to target IE, Firefox, or a mobile browser.

**Comment by mrzmyr** [comment]
Sounds great to have a possibility to use a config file.

**Comment by agzam** [comment]
is this still relevant? I can't find a way to make Elementor (or webDriver`) respect protractor.conf settings. Is there a way?

**Comment by AnkitKhowal** [comment]
i tried using elementor and i am getting  an error  UnknownError: chrome not reachable.
I tried the url:elementor https://angularjs.org --chrome="--remote-debugging-port=9222 --disable-web-security".
and i also trying to test  it with elementor localhost:9000 everything works fine but the chrome instance comes up shows up nothing and i get a error after some time ECONNREFUSED connect ECONNREFUSED

**Comment by AnkitKhowal** [comment]
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
