### ISSUE TITLE
throwing Unhandled error event

### ISSUE THREAD

**Issue by vivekbrahmadandi** [andresdominguez/elementor#36]
```
Creating protractor configuration file
Starting protractor
Running command: [node C:\Users\vivekb\AppData\Roaming\npm\node_modules\elementor\node_modules\protractor\built\cli.js --elementExplorer true --debuggerServerPort 6969 C:\Users\vivekb\AppData\Local\Temp\protractor-conf116522-7268-1li19mn]
[11:58:25] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[11:58:29] I/protractor -
[11:58:29] I/protractor - ------- Element Explorer -------
[11:58:29] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.com/angular/protractor
[11:58:29] I/protractor -
[11:58:29] I/protractor - Type <tab> to see a list of locator strategies.
[11:58:29] I/protractor - Use the `list` helper function to find elements by strategy:
[11:58:29] I/protractor -   e.g., list(by.binding('')) gets all bindings.
[11:58:29] I/protractor -
Server listening on 127.0.0.1:6969
Done starting protractor
Starting elementor
Elementor is listening on http://localhost:13000
Getting page at: https://eotar-devel.moremagic.com/ui_topup/erecharge/aui
Connected. Sending command: browser.get('https://eotar-devel.moremagic.com/ui_topup/erecharge/aui');
Elementor is ready!
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
```

**Comment by andresdominguez** [comment]
Hello:

Thank you for reporting this issue. Which version of node and protractor are you using?

**Comment by jonmitch1991** [comment]
Really like the tool, but I'm having a similar issue quite a bit too.

This is node v6.6.0 and protractor v2.5.1

Starting elementor
Elementor is listening on http://localhost:13000
Elementor is ready!
Popup input [element.all(by.css('div.alert.alert-info'))]
Connected. Sending command: element.all(by.css('div.alert.alert-info'))
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1036:11)
    at Pipe.onread (net.js:564:26)

**Comment by a-inglese** [comment]
Hello! First of all, thanks for this great tool, it has helped me a lot in the past

Sadly, I started having the same problem described here :(
Details are as follow. Thanks for your time.

Protractor: 4.0.9
Node: 6.3.0

**Console Log**

```
Creating protractor configuration file
Starting protractor
Running command: [node /usr/local/lib/node_modules/elementor/node_modules/protractor/built/cli.js --elementExplorer true --debuggerServerPort 6969 /tmp/protractor-conf1161119-27233-72cmo3.saijzqto6r]
[13:37:58] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[13:38:01] I/protractor -
[13:38:01] I/protractor - ------- Element Explorer -------
[13:38:01] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.com/angular/protractor
[13:38:01] I/protractor -
[13:38:01] I/protractor - Type <tab> to see a list of locator strategies.
[13:38:01] I/protractor - Use the `list` helper function to find elements by strategy:
[13:38:01] I/protractor -   e.g., list(by.binding('')) gets all bindings.
[13:38:01] I/protractor -
Server listening on 127.0.0.1:6969
Done starting protractor
Starting elementor
Elementor is listening on http://localhost:13000
Getting page at: http://www.despegar.com.ar/cp/shop/search/C982/C6624/2017-01-19/2017-01-26/2/0/0/NA/2017-01-19/2017-01-26/2
Connected. Sending command: browser.get('http://www.despegar.com.ar/cp/shop/search/C982/C6624/2017-01-19/2017-01-26/2/0/0/NA/2017-01-19/2017-01-26/2');
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1008:11)
    at Pipe.onread (net.js:563:26)

```

**Comment by gustavolira** [comment]
same problem here

**Comment by TamerHussien** [comment]
i was having the problem cause i didn't install java ..... after install it working perfectly
