### ISSUE TITLE
Running elementor momentarily starts Chrome browser/shuts down, exceptions are thrown in webdriver server console

### ISSUE THREAD

**Issue by jaisannaidu79** [andresdominguez/elementor#46]
Hi Andres,

Thank you so much for providing us with such an awesome tool. It has made my life so much easier and faster. Please continue your great work. Really appreciate it.

Any idea on how to fix the issue below? Let me know if you need more info. Thanks.

My Configuration:
Windows 10 Bootcamp on a Macbook
Node: 4.4.7
Protractor: 4.0.3
WebDriver: 2.53.1
Elementor: 2.1.0
Chrome: 54.0.2840.71 m (64-bit)
-------------------------------------------------
When I run elementor: C:\git\ppm-ux>elementor http://localhost:3000
I get the following:
C:\git\ppm-ux>elementor http://localhost:3000
Creating protractor configuration file
Starting protractor
Running command: [node C:\Users\naija03.TANT-A01\AppData\Roaming\npm\node_modules\elementor\node_modules\protractor\built\cli.js --elementExplorer true --debuggerServerPort 6969 C:\Users\NAIJA0~1.TAN\AppData\Local\Temp\protractor-conf116921-6160-ky2m1b]
[10:44:24] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
-------------------------------------------------------------------------------------------------------------
I get the following from the webdriver console:
C:\git\ppm-ux>webdriver-manager start
[10:47:43] I/start - java -jar C:\Users\naija03.TANT-A01\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-2.53.1.jar -Dwebdriver.chrome.driver=C:\Users\naija03.TANT-A01\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.22.exe -Dwebdriver.ie.driver=C:\Users\naija03.TANT-A01\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\IEDriverServer_x64_2.53.1.exe
[10:47:43] I/start - seleniumProcess.pid: 10296
10:47:43.260 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to C:\Users\naija03.TANT-A01\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.22.exe
Setting system property webdriver.ie.driver to C:\Users\naija03.TANT-A01\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\IEDriverServer_x64_2.53.1.exe
10:47:43.313 INFO - Java: Oracle Corporation 25.101-b13
10:47:43.313 INFO - OS: Windows 10 10.0 amd64
10:47:43.316 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
10:47:43.347 INFO - Driver class not found: com.opera.core.systems.OperaDriver
10:47:43.347 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
10:47:43.364 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WIN10
10:47:43.364 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
10:47:43.364 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
10:47:43.424 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
10:47:43.424 INFO - Selenium Server is up and running
10:47:46.918 INFO - Executing: [new session: Capabilities [{browserName=chrome, chromeOptions={args=[--load-extension=C:/Users/naija03.TANT-A01/AppData/Roaming/npm/node_modules/elementor/extension]}}]])
10:47:46.919 INFO - Creating a new session for Capabilities [{browserName=chrome, chromeOptions={args=[--load-extension=C:/Users/naija03.TANT-A01/AppData/Roaming/npm/node_modules/elementor/extension]}}]
Starting ChromeDriver 2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b) on port 23911
Only local connections are allowed.
10:47:49.818 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'naija03-win10a', ip: '10.132.141.236', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
        at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
        at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
        at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
        at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
        at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
        at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
        at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
        at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
        at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'naija03-win10a', ip: '10.132.141.236', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
        ... 9 more
Caused by: org.openqa.selenium.SessionNotCreatedException: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"6076.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.99 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'naija03-win10a', ip: '10.132.141.236', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:138)
        ... 14 more
10:47:49.818 WARN - Exception: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"6076.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.99 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'naija03-win10a', ip: '10.132.141.236', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver

**Comment by jaisannaidu79** [comment]
Updated, the version of Protractor to 4.0.9 and Chromedriver to 2.24 and elementor to 2.1.0. Which fixed this issue for me. Thanks.

**Comment by TamerHussien** [comment]
version of Protractor 5.3 and Chromedriver to 2.35 and elementor to 2.1.0
still have the same problem
