### ISSUE TITLE
Getting Error Launching Elementor

### ISSUE THREAD

**Issue by DarthOpto** [andresdominguez/elementor#63]
When I attempt to launch elementor `elementor http://google.com` I am getting the following error

```
Creating protractor configuration file
fs.js:140
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:140:9)
    at Object.fs.write (fs.js:656:14)
    at /usr/local/lib/node_modules/elementor/lib/config-helper.js:21:8
    at /usr/local/lib/node_modules/elementor/node_modules/temp/lib/temp.js:252:7
    at FSReqWrap.oncomplete (fs.js:152:20)```

**Comment by wrodr2013** [comment]
Same here, started after I updated to Node v8.11.3
Uninstall, reinstall Node v6.11.2 and its working for me again.

**Comment by kedziorm** [comment]
I had this problem as well. 
As mentioned by @wrodr2013 when I switched to previous version of Node, I was able to use `Elementor`. @DarthOpto you don't need to uninstall Node, try to install Node Version Manager for easier switching between Node's versions.

I guess that this might be related with `protractor --elementExplorer` that is also unable to work with the latest version of Node.
