### ISSUE TITLE
Elementor extension not working with latest node version v11.13.0

### ISSUE THREAD

**Issue by ajoshiakshay** [andresdominguez/elementor#68]
Hi,
Elementor is not working with latest node version v11.13.0

Below error is shown when running the elementor

Creating protractor configuration file
fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.write (fs.js:556:14)
    at /usr/local/lib/node_modules/elementor/lib/config-helper.js:21:8
    at /usr/local/lib/node_modules/elementor/node_modules/temp/lib/temp.js:252:7
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)

**Comment by gtgunarathna** [comment]
i also got the same error, is there any workaround for this ?

**Comment by ajoshiakshay** [comment]
Workaround would be to reduce the node version may be to node version 8.

**Comment by anaidych** [comment]
It works only with node 6.11.2 and chrome driver lower than 2.4
